services:
  api:
    build: .
    command: npm run dev
    restart: always
    ports:
      - "3333:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: blog
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  redis:
    image: redis
    command: redis-server --appendonly yes --save 7200 1
    volumes:
      - ./volumes/redis:/data
    ports:
      - 6379:6379
